### ISSUE TITLE
Docker: Databse is written to /donetick.db

### ISSUE THREAD

**Issue by chrisb86** [donetick/donetick#17]
The docker image uses a wrong or undocumented path for the database. It is created at _/donetick.db_ and thus not in the persistent storage with the proposed compose file.

The path to the databse file should be corrected to be inside _/usr/src/app/data_ or the README should be corrected.

A volume mapping in the compose file like ```./volumes/donetick-db/donetick.db:/donetick.db:rw```fixes this as a workaround.

**Comment by meauxt** [comment]
I added to the example the need to specify `DT_SQLITE_PATH` env for now that should have both examples working and able to persist
