### ISSUE TITLE
Minor spelling error

### ISSUE THREAD

**Issue by gusjustgus1** [donetick/donetick#19]
![Capture](https://github.com/user-attachments/assets/e0229ca0-4bb6-43fb-89e9-fcc3041e4b6e)
I just installed this on my local Unraid server via the Community Content.  I spotted a minor spelling error when adding a new chore:
"Descritpion" should be "Description", screenshot attached as reference.

**Comment by meauxt** [comment]
Thanks for the catch @gusjustgus1, just corrected it, will be updated in the next release!
