### ISSUE TITLE
[Feature Request] Add support for webdav server

### ISSUE THREAD

**Issue by TheZoker** [donetick/donetick#2]
I'm not sure if this is something that you would consider, but it would be amazing, if I could use donetick as a frontend web service for my baikal webdav todo list server. There is currently not really a nice solution for managing webdav todos in the web, so this would be amazin!

Goal would be to display tasks from any webdav server in donetick and sync any changes back to the webdav server.

**Comment by meauxt** [comment]
Hi @TheZoker ! That's a good idea! I don't have experience with Webdav. but if someone decides to implement client and sync donetick will be happy to discuss this further. going to add `help wanted` label. if there is interest i can move it to the project roadmap

**Comment by meauxt** [comment]
I think I'll close this issue for now. Based on my research, DoneTick could potentially be a standalone WebDAV server in the future, but I'm uncertain about the reverse integration.

For now, let's prioritize improving DoneTick's core functionality. Perhaps in the future, I or someone more experienced can revisit this WebDAV integration idea.
