### ISSUE TITLE
Copy Token - Nothig Copied

### ISSUE THREAD

**Issue by thekiwismarthome** [donetick/donetick#27]
Love the integration so far, tried to set it up with HA to get the full experience but no matter what I try, I cannot copy the token required, any help would be awesome thanks
Tried in Edge and Chrome.
Running it in a HA Add-on

**Comment by meauxt** [comment]
I think have to do with homeassistant native app. can you try to go there using chrome and see if you seeing same issue?

**Comment by thekiwismarthome** [comment]
I use Chrome normally, I used Edge afterwards just on case

**Comment by thekiwismarthome** [comment]
Yeah same issue sorry, just doesn't copy anything

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by meauxt** [comment]
Sorry when I read you original comment I totally miss the part you said `Tried in Edge and Chrome.`
Can you share you device info so I can replicate?
Can you try this website from same browser and let me know if the blue copy button working (trying to see if permissions related) https://codepen.io/foxbeefly/pen/dyWbQgJ

**Comment by thekiwismarthome** [comment]
david@stylus.co.za
That copied OK

**Comment by deltaviper** [comment]
Can confirm this issue on multiple devices (Samsung Galaxy S24 Ultra and Mcirosoft Surface pro) using Edge and Chrome, UI does not load in IE mode or in Firefox. No copy buttons work. Copy button on the wbesite linked above did work

**Comment by meauxt** [comment]
a walkaround should be available in the next release!  @thekiwismarthome @deltaviper

**Comment by meauxt** [comment]
<img width="707" alt="image" src="https://github.com/user-attachments/assets/5e6427a6-1c60-4afb-8247-bd13062e3442" />
Please update to [0.0.22](https://github.com/donetick/donetick/releases/tag/v0.0.22)! you should be able to select show token and then manually select it! @thekiwismarthome @deltaviper

**Comment by thekiwismarthome** [comment]
this worked thanks

**Comment by deltaviper** [comment]
Yep, all good now.
