### ISSUE TITLE
[Feature Request] Prebuild docker image

### ISSUE THREAD

**Issue by TheZoker** [donetick/donetick#3]
Would be awesome, if you could add a workflow action, which prebuilds the docker image and uploads it to dockerhub or ghcr.io

**Comment by meauxt** [comment]
Hey @TheZoker ! I started working on this, hopefully will have an update soon!

**Comment by meauxt** [comment]
@TheZoker  Docker image available now in docker hub you! https://hub.docker.com/repository/docker/donetick/donetick/general 
let me know if you have an issue running it!

**Comment by Buster14** [comment]
Hi, after pulling this image,
Can you tell exactly what command must be run?
I'm running this in a debian 12 container..
