### ISSUE TITLE
Upgraded to last release - authorization/middleware.go:120 middleware.jwt.Unauthorizedcode403messageyou don't have permission to access this resource

### ISSUE THREAD

**Issue by yoannfelix** [donetick/donetick#30]
Hello,

I upgraded to the last release on my unraid, and I am getting the following message.

```
2024/12/01 18:47:00 /home/runner/work/donetick/donetick/internal/user/repo/repository.go:61 record not found
[1.314ms] [rows:0] SELECT u.*, 'active' as  subscription, '2999-12-31' as expiration FROM users u WHERE username = "yoannfelix" ORDER BY `u`.`id` LIMIT 1
2024-12-01T18:47:00.123Z        info    authorization/middleware.go:120 middleware.jwt.Unauthorizedcode403messageyou don't have permission to access this resource
```
The web page just shows '404'.

**Comment by meauxt** [comment]
hi @yoannfelix !
seems your change did not persist after the update. could be the database path was not configured. check out the last few post in https://github.com/donetick/donetick/issues/7 to make sure you have the right configration

**Comment by yoannfelix** [comment]
Oh, thanks! I didnt know there was more to the thread. I had initially installed it using those instructions.

It ended up being the variable DT_SQLITE_PATH that was missing I believe. Thanks again for pointing me there.
