### ISSUE TITLE
HA: Failed to connect to Donetick

### ISSUE THREAD

**Issue by airbornetrooper82573** [donetick/donetick#35]
I am trying to connect HA to DoneTick. I have Donetick running and available at https://donetick.mydomainname.com and setup the access code. I've tried putting in the ip:2021 and my url and it keeps failing. Is there something I need to add in the selfhosted.yaml?

**Comment by airbornetrooper82573** [comment]
App shows I am running V0.1.80

**Comment by meauxt** [comment]
please make sure you are running HA Addon 1.0.18. Also you can just point it to the internal IP that you have.  feel free to reopen the issue if still happening.
