### ISSUE TITLE
Labels on task not working with other user in circle

### ISSUE THREAD

**Issue by orlahowell** [donetick/donetick#38]
I created some tasks and added a label to each of them. Then invited a friend to the circle and when I assigned a task to them react errored and all we saw was the 404 error boundary.

When I removed the label from the task then they could see the task with no error.

**Comment by meauxt** [comment]
Hi @orlahowell ! 
Thank you for reporting this! I just released and should be fixed in [v0.0.21](https://github.com/donetick/donetick/releases/tag/v0.0.21)
