### ISSUE TITLE
Unraid Docker stopps when a task gets ticked

### ISSUE THREAD

**Issue by BastiKA84** [donetick/donetick#42]
Everytime I tick a task, the docker stops. I can then run it again, but next tick makes the docker stop again.

This is the howl log between starting and the stoppage:

text  error  warn  system  array  login  

[Fx] INVOKE             donetick.com/core/internal/circle.Routes()
[Fx] RUN        provide: donetick.com/core/internal/circle.NewHandler()
2024/12/10 16:44:40 Registering routes
[Fx] INVOKE             donetick.com/core/internal/thing.Routes()
[Fx] RUN        provide: donetick.com/core/internal/thing.NewHandler()
[Fx] INVOKE             donetick.com/core/internal/thing.Webhooks()
[Fx] RUN        provide: donetick.com/core/internal/thing.NewWebhook()
[Fx] INVOKE             donetick.com/core/internal/label.Routes()
[Fx] RUN        provide: donetick.com/core/internal/label.NewHandler()
[Fx] INVOKE             donetick.com/core/frontend.Routes()
[Fx] RUN        provide: donetick.com/core/frontend.NewHandler()
[Fx] INVOKE             main.main.func1()
[Fx] HOOK OnStart               main.newServer.func1() executing (caller: main.newServer)
[Fx] HOOK OnStart               main.newServer.func1() called by main.newServer ran successfully in 7.847432ms
[Fx] RUNNING
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xad44af]

goroutine 118 [running]:
donetick.com/core/internal/notifier/telegram.(*TelegramNotifier).SendChoreCompletion(0x0, {0x19f8018?, 0xc00063e000?}, 0xc000195100, 0xc00017cd20)
        /home/runner/work/donetick/donetick/internal/notifier/telegram/telegram.go:78 +0x36f
donetick.com/core/internal/chore.(*Handler).completeChore.func1()
        /home/runner/work/donetick/donetick/internal/chore/handler.go:932 +0x45
created by donetick.com/core/internal/chore.(*Handler).completeChore in goroutine 75
        /home/runner/work/donetick/donetick/internal/chore/handler.go:931 +0xd36
[GIN-debug] DELETE /chores/:id               --> donetick.com/core/internal/chore.(*Handler).deleteChore-fm (3 handlers)
[GIN-debug] GET    /users/                   --> donetick.com/core/internal/user.Routes.(*Handler).GetAllUsers.func3 (4 handlers)
[GIN-debug] GET    /users/profile            --> donetick.com/core/internal/user.(*Handler).GetUserProfile-fm (4 handlers)
[GIN-debug] PUT    /users                    --> donetick.com/core/internal/user.(*Handler).UpdateUserDetails-fm (4 handlers)
[GIN-debug] POST   /users/tokens             --> donetick.com/core/internal/user.(*Handler).CreateLongLivedToken-fm (4 handlers)
[GIN-debug] GET    /users/tokens             --> donetick.com/core/internal/user.(*Handler).GetAllUserToken-fm (4 handlers)
[GIN-debug] DELETE /users/tokens/:id         --> donetick.com/core/internal/user.(*Handler).DeleteUserToken-fm (4 handlers)
[GIN-debug] PUT    /users/targets            --> donetick.com/core/internal/user.(*Handler).UpdateNotificationTarget-fm (4 handlers)
[GIN-debug] PUT    /users/change_password    --> donetick.com/core/internal/user.(*Handler).updateUserPasswordLoggedInOnly-fm (4 handlers)
[GIN-debug] POST   /auth/                    --> donetick.com/core/internal/user.(*Handler).signUp-fm (3 handlers)
[GIN-debug] POST   /auth/login               --> github.com/appleboy/gin-jwt/v2.(*GinJWTMiddleware).LoginHandler-fm (3 handlers)
[GIN-debug] GET    /auth/refresh             --> github.com/appleboy/gin-jwt/v2.(*GinJWTMiddleware).RefreshHandler-fm (3 handlers)
[GIN-debug] POST   /auth/:provider/callback  --> donetick.com/core/internal/user.(*Handler).thirdPartyAuthCallback-fm (3 handlers)
[GIN-debug] POST   /auth/reset               --> donetick.com/core/internal/user.(*Handler).resetPassword-fm (3 handlers)
[GIN-debug] POST   /auth/password            --> donetick.com/core/internal/user.(*Handler).updateUserPassword-fm (3 handlers)
[GIN-debug] GET    /circles/members          --> donetick.com/core/internal/circle.(*Handler).GetCircleMembers-fm (3 handlers)
[GIN-debug] GET    /circles/members/requests --> donetick.com/core/internal/circle.(*Handler).GetPendingCircleMembers-fm (3 handlers)
[GIN-debug] PUT    /circles/members/requests/accept --> donetick.com/core/internal/circle.(*Handler).AcceptJoinRequest-fm (3 handlers)
[GIN-debug] GET    /circles/                 --> donetick.com/core/internal/circle.(*Handler).GetUserCircles-fm (3 handlers)
[GIN-debug] POST   /circles/join             --> donetick.com/core/internal/circle.(*Handler).JoinCircle-fm (3 handlers)
[GIN-debug] DELETE /circles/leave            --> donetick.com/core/internal/circle.(*Handler).LeaveCircle-fm (3 handlers)
[GIN-debug] DELETE /circles/:id/members/delete --> donetick.com/core/internal/circle.(*Handler).DeleteCircleMember-fm (3 handlers)
[GIN-debug] POST   /things                   --> donetick.com/core/internal/thing.(*Handler).CreateThing-fm (3 handlers)
[GIN-debug] PUT    /things/:id/state         --> donetick.com/core/internal/thing.(*Handler).UpdateThingState-fm (3 handlers)
[GIN-debug] PUT    /things                   --> donetick.com/core/internal/thing.(*Handler).UpdateThing-fm (3 handlers)
[GIN-debug] GET    /things                   --> donetick.com/core/internal/thing.(*Handler).GetAllThings-fm (3 handlers)
[GIN-debug] GET    /things/:id/history       --> donetick.com/core/internal/thing.(*Handler).GetThingHistory-fm (3 handlers)
[GIN-debug] DELETE /things/:id               --> donetick.com/core/internal/thing.(*Handler).DeleteThing-fm (3 handlers)
[GIN-debug] GET    /webhooks/things/:id/state/change --> donetick.com/core/internal/thing.(*Webhook).ChangeThingState-fm (3 handlers)
[GIN-debug] GET    /webhooks/things/:id/state --> donetick.com/core/internal/thing.(*Webhook).UpdateThingState-fm (3 handlers)
[GIN-debug] GET    /labels                   --> donetick.com/core/internal/label.(*Handler).getLabels-fm (3 handlers)
[GIN-debug] POST   /labels                   --> donetick.com/core/internal/label.(*Handler).createLabel-fm (3 handlers)
[GIN-debug] PUT    /labels                   --> donetick.com/core/internal/label.(*Handler).updateLabel-fm (3 handlers)
[GIN-debug] DELETE /labels/:id               --> donetick.com/core/internal/label.(*Handler).deleteLabel-fm (3 handlers)
2024-12-10T16:44:40.443Z        debug   migrations/base.go:63   Skipping migration %s as it is already applied20241123_migrate_label_to_labels_v2
2024-12-10T16:44:40.443Z        info    migrations/base.go:97   Migrations: 0 successful, 0 failed, 1 skipped, 1 total in registry
Applied 0 migrations!
2024-12-10T16:44:40.443Z        debug   notifier/scheduler.go:44        Scheduler started
2024-12-10T16:44:40.444Z        debug   notifier/scheduler.go:70        Scheduler running  NOTIFICATION_SCHEDULER  time2024-12-10 16:44:40.443978403 +0000 UTC m=+0.471238520
2024-12-10T16:44:40.444Z        debug   notifier/scheduler.go:52        Getting pending notifications count 0
2024-12-10T16:44:40.444Z        debug   notifier/scheduler.go:81        Scheduler job completed NOTIFICATION_SCHEDULER  time550.606µs

2024/12/10 16:44:53 /home/runner/work/donetick/donetick/internal/chore/repo/repository.go:38
[0.066ms] [rows:1] SELECT * FROM `chore_assignees` WHERE `chore_assignees`.`chore_id` = 5

2024/12/10 16:44:53 /home/runner/work/donetick/donetick/internal/chore/repo/repository.go:38
[0.055ms] [rows:0] SELECT * FROM `chore_labels` WHERE `chore_labels`.`chore_id` = 5

2024/12/10 16:44:53 /home/runner/work/donetick/donetick/internal/chore/repo/repository.go:38
[0.080ms] [rows:0] SELECT * FROM `thing_chores` WHERE `thing_chores`.`chore_id` = 5

2024/12/10 16:44:53 /home/runner/work/donetick/donetick/internal/chore/repo/repository.go:38
[0.564ms] [rows:1] SELECT * FROM `chores` WHERE `chores`.`id` = 5 ORDER BY `chores`.`id` LIMIT 1

2024/12/10 16:44:53 /home/runner/work/donetick/donetick/internal/chore/repo/repository.go:38
[0.075ms] [rows:1] SELECT * FROM `chore_assignees` WHERE `chore_assignees`.`chore_id` = 5

2024/12/10 16:44:53 /home/runner/work/donetick/donetick/internal/chore/repo/repository.go:38
[0.047ms] [rows:0] SELECT * FROM `chore_labels` WHERE `chore_labels`.`chore_id` = 5

2024/12/10 16:44:53 /home/runner/work/donetick/donetick/internal/chore/repo/repository.go:38
[0.044ms] [rows:0] SELECT * FROM `thing_chores` WHERE `thing_chores`.`chore_id` = 5

2024/12/10 16:44:53 /home/runner/work/donetick/donetick/internal/chore/repo/repository.go:38
[0.453ms] [rows:1] SELECT * FROM `chores` WHERE `chores`.`id` = 5 ORDER BY `chores`.`id` LIMIT 1

** Press ANY KEY to close this window **

**Comment by meauxt** [comment]
do you have telegram configured? if not try updating to the newest version [0.22](https://github.com/donetick/donetick/releases/tag/v0.0.22)  and let me know if that works

**Comment by jmerifjKriwe** [comment]
Dockerfile is still providing 0.18
No update available https://hub.docker.com/r/donetick/donetick

**Comment by meauxt** [comment]
Sorry missed that please check it out now!

**Comment by BastiKA84** [comment]
Yeah, I did the update. Now it does not know my user anymore 🤷‍♀️
I will have to create a new User and some works. I will do that on monday and report here.

**Comment by meauxt** [comment]
@BastiKA84 I remember people here had issues with their configuration you might find this useful:
https://github.com/donetick/donetick/issues/7

**Comment by BastiKA84** [comment]
I tried what was postet in #7. But now I cannot log in to donetick anymore. All I get is 404... literaly 
![image](https://github.com/user-attachments/assets/c1614709-9995-47b6-807e-5107073c78f1)


This is the Log:
text  error  warn  system  array  login  

[Fx] RUN        provide: donetick.com/core/internal/notifier.NewNotifier()
[Fx] RUN        provide: donetick.com/core/internal/notifier/repo.NewNotificationRepository()
[Fx] RUN        provide: donetick.com/core/internal/notifier.NewScheduler()
[Fx] RUN        provide: main.newServer()
[Fx] RUN        provide: donetick.com/core/internal/circle/repo.NewCircleRepository()
[Fx] RUN        provide: donetick.com/core/internal/notifier/service.NewNotificationPlanner()
[Fx] RUN        provide: donetick.com/core/internal/thing/repo.NewThingRepository()
[Fx] RUN        provide: donetick.com/core/internal/label/repo.NewLabelRepository()
[Fx] RUN        provide: donetick.com/core/internal/chore.NewHandler()
[Fx] RUN        provide: donetick.com/core/internal/authorization.NewAuthMiddleware()
[Fx] INVOKE             donetick.com/core/internal/chore.APIs()
[Fx] RUN        provide: donetick.com/core/internal/chore.NewAPI()
[Fx] RUN        provide: donetick.com/core/internal/utils.NewRateLimiter()
[Fx] INVOKE             donetick.com/core/internal/user.Routes()
[Fx] RUN        provide: donetick.com/core/internal/email.NewEmailSender()
[Fx] RUN        provide: donetick.com/core/internal/user.NewHandler()
[Fx] INVOKE             donetick.com/core/internal/circle.Routes()
[Fx] RUN        provide: donetick.com/core/internal/circle.NewHandler()
2024/12/17 09:01:10 Registering routes
[Fx] INVOKE             donetick.com/core/internal/thing.Routes()
[Fx] RUN        provide: donetick.com/core/internal/thing.NewHandler()
[Fx] INVOKE             donetick.com/core/internal/thing.Webhooks()
[Fx] RUN        provide: donetick.com/core/internal/thing.NewWebhook()
[Fx] INVOKE             donetick.com/core/internal/label.Routes()
[Fx] RUN        provide: donetick.com/core/internal/label.NewHandler()
[Fx] INVOKE             donetick.com/core/frontend.Routes()
[Fx] RUN        provide: donetick.com/core/frontend.NewHandler()
[Fx] INVOKE             main.main.func1()
[Fx] HOOK OnStart               main.newServer.func1() executing (caller: main.newServer)
[Fx] HOOK OnStart               main.newServer.func1() called by main.newServer ran successfully in 7.482482ms
[Fx] RUNNING
[GIN-debug] GET    /chores/                  --> donetick.com/core/internal/chore.(*Handler).getChores-fm (3 handlers)
[GIN-debug] GET    /chores/archived          --> donetick.com/core/internal/chore.(*Handler).getArchivedChores-fm (3 handlers)
[GIN-debug] PUT    /chores/                  --> donetick.com/core/internal/chore.(*Handler).editChore-fm (3 handlers)
[GIN-debug] PUT    /chores/:id/priority      --> donetick.com/core/internal/chore.(*Handler).updatePriority-fm (3 handlers)
[GIN-debug] POST   /chores/                  --> donetick.com/core/internal/chore.(*Handler).createChore-fm (3 handlers)
[GIN-debug] GET    /chores/:id               --> donetick.com/core/internal/chore.(*Handler).getChore-fm (3 handlers)
[GIN-debug] GET    /chores/:id/details       --> donetick.com/core/internal/chore.(*Handler).GetChoreDetail-fm (3 handlers)
[GIN-debug] GET    /chores/:id/history       --> donetick.com/core/internal/chore.(*Handler).GetChoreHistory-fm (3 handlers)
[GIN-debug] PUT    /chores/:id/history/:history_id --> donetick.com/core/internal/chore.(*Handler).ModifyHistory-fm (3 handlers)
[GIN-debug] DELETE /chores/:id/history/:history_id --> donetick.com/core/internal/chore.(*Handler).DeleteHistory-fm (3 handlers)
[GIN-debug] POST   /chores/:id/do            --> donetick.com/core/internal/chore.(*Handler).completeChore-fm (3 handlers)
[GIN-debug] POST   /chores/:id/skip          --> donetick.com/core/internal/chore.(*Handler).skipChore-fm (3 handlers)
[GIN-debug] PUT    /chores/:id/assignee      --> donetick.com/core/internal/chore.(*Handler).updateAssignee-fm (3 handlers)
[GIN-debug] PUT    /chores/:id/dueDate       --> donetick.com/core/internal/chore.(*Handler).updateDueDate-fm (3 handlers)
[GIN-debug] DELETE /chores/:id               --> donetick.com/core/internal/chore.(*Handler).deleteChore-fm (3 handlers)
[GIN-debug] GET    /api/v1/chore             --> donetick.com/core/internal/chore.(*API).GetAllChores-fm (4 handlers)
[GIN-debug] GET    /users/                   --> donetick.com/core/internal/user.Routes.(*Handler).GetAllUsers.func3 (4 handlers)
[GIN-debug] GET    /users/profile            --> donetick.com/core/internal/user.(*Handler).GetUserProfile-fm (4 handlers)
[GIN-debug] PUT    /users                    --> donetick.com/core/internal/user.(*Handler).UpdateUserDetails-fm (4 handlers)
[GIN-debug] POST   /users/tokens             --> donetick.com/core/internal/user.(*Handler).CreateLongLivedToken-fm (4 handlers)
[GIN-debug] GET    /users/tokens             --> donetick.com/core/internal/user.(*Handler).GetAllUserToken-fm (4 handlers)
[GIN-debug] DELETE /users/tokens/:id         --> donetick.com/core/internal/user.(*Handler).DeleteUserToken-fm (4 handlers)
[GIN-debug] PUT    /users/targets            --> donetick.com/core/internal/user.(*Handler).UpdateNotificationTarget-fm (4 handlers)
[GIN-debug] PUT    /users/change_password    --> donetick.com/core/internal/user.(*Handler).updateUserPasswordLoggedInOnly-fm (4 handlers)
[GIN-debug] POST   /auth/:provider/callback  --> donetick.com/core/internal/user.(*Handler).thirdPartyAuthCallback-fm (3 handlers)
[GIN-debug] POST   /auth/                    --> donetick.com/core/internal/user.(*Handler).signUp-fm (3 handlers)
[GIN-debug] POST   /auth/login               --> github.com/appleboy/gin-jwt/v2.(*GinJWTMiddleware).LoginHandler-fm (3 handlers)
[GIN-debug] GET    /auth/refresh             --> github.com/appleboy/gin-jwt/v2.(*GinJWTMiddleware).RefreshHandler-fm (3 handlers)
[GIN-debug] POST   /auth/reset               --> donetick.com/core/internal/user.(*Handler).resetPassword-fm (3 handlers)
[GIN-debug] POST   /auth/password            --> donetick.com/core/internal/user.(*Handler).updateUserPassword-fm (3 handlers)
[GIN-debug] GET    /circles/members          --> donetick.com/core/internal/circle.(*Handler).GetCircleMembers-fm (3 handlers)
[GIN-debug] GET    /circles/members/requests --> donetick.com/core/internal/circle.(*Handler).GetPendingCircleMembers-fm (3 handlers)
[GIN-debug] PUT    /circles/members/requests/accept --> donetick.com/core/internal/circle.(*Handler).AcceptJoinRequest-fm (3 handlers)
[GIN-debug] GET    /circles/                 --> donetick.com/core/internal/circle.(*Handler).GetUserCircles-fm (3 handlers)
[GIN-debug] POST   /circles/join             --> donetick.com/core/internal/circle.(*Handler).JoinCircle-fm (3 handlers)
[GIN-debug] DELETE /circles/leave            --> donetick.com/core/internal/circle.(*Handler).LeaveCircle-fm (3 handlers)
[GIN-debug] DELETE /circles/:id/members/delete --> donetick.com/core/internal/circle.(*Handler).DeleteCircleMember-fm (3 handlers)
[GIN-debug] POST   /things                   --> donetick.com/core/internal/thing.(*Handler).CreateThing-fm (3 handlers)
[GIN-debug] PUT    /things/:id/state         --> donetick.com/core/internal/thing.(*Handler).UpdateThingState-fm (3 handlers)
[GIN-debug] PUT    /things                   --> donetick.com/core/internal/thing.(*Handler).UpdateThing-fm (3 handlers)
[GIN-debug] GET    /things                   --> donetick.com/core/internal/thing.(*Handler).GetAllThings-fm (3 handlers)
[GIN-debug] GET    /things/:id/history       --> donetick.com/core/internal/thing.(*Handler).GetThingHistory-fm (3 handlers)
[GIN-debug] DELETE /things/:id               --> donetick.com/core/internal/thing.(*Handler).DeleteThing-fm (3 handlers)
[GIN-debug] GET    /webhooks/things/:id/state/change --> donetick.com/core/internal/thing.(*Webhook).ChangeThingState-fm (3 handlers)
[GIN-debug] GET    /webhooks/things/:id/state --> donetick.com/core/internal/thing.(*Webhook).UpdateThingState-fm (3 handlers)
[GIN-debug] GET    /labels                   --> donetick.com/core/internal/label.(*Handler).getLabels-fm (3 handlers)
[GIN-debug] POST   /labels                   --> donetick.com/core/internal/label.(*Handler).createLabel-fm (3 handlers)
[GIN-debug] PUT    /labels                   --> donetick.com/core/internal/label.(*Handler).updateLabel-fm (3 handlers)
[GIN-debug] DELETE /labels/:id               --> donetick.com/core/internal/label.(*Handler).deleteLabel-fm (3 handlers)
2024-12-17T09:01:10.259Z        debug   migrations/base.go:63   Skipping migration %s as it is already applied20241123_migrate_label_to_labels_v2
2024-12-17T09:01:10.259Z        debug   migrations/base.go:63   Skipping migration %s as it is already applied20241212_migrate_chat_id_to_notification_target
2024-12-17T09:01:10.259Z        info    migrations/base.go:97   Migrations: 0 successful, 0 failed, 2 skipped, 2 total in registry
Applied 0 migrations!
2024-12-17T09:01:10.259Z        debug   notifier/scheduler.go:43        Scheduler started
2024-12-17T09:01:10.259Z        debug   notifier/scheduler.go:84        Scheduler running  NOTIFICATION_CLEANUP  time2024-12-17 09:01:10.259432697 +0000 UTC m=+0.427327043
2024-12-17T09:01:10.259Z        debug   notifier/scheduler.go:84        Scheduler running  NOTIFICATION_SCHEDULER  time2024-12-17 09:01:10.259426035 +0000 UTC m=+0.427320391
2024-12-17T09:01:10.260Z        debug   notifier/scheduler.go:95        Scheduler job completed NOTIFICATION_CLEANUP  time: 0s
2024-12-17T09:01:10.260Z        debug   notifier/scheduler.go:62        Getting pending notifications count 0
2024-12-17T09:01:10.260Z        debug   notifier/scheduler.go:95        Scheduler job completed NOTIFICATION_SCHEDULER  time: 1.308348ms

2024/12/17 09:01:31 /home/runner/work/donetick/donetick/internal/user/repo/repository.go:62 record not found
[0.348ms] [rows:0] SELECT u.*, 'active' as  subscription, '2999-12-31' as expiration FROM users u WHERE username = "Bastian" ORDER BY `u`.`id` LIMIT 1
2024-12-17T09:01:31.130Z        info    authorization/middleware.go:120 middleware.jwt.Unauthorizedcode403messageyou don't have permission to access this resource

2024/12/17 09:01:31 /home/runner/work/donetick/donetick/internal/user/repo/repository.go:62 record not found
[0.498ms] [rows:0] SELECT u.*, 'active' as  subscription, '2999-12-31' as expiration FROM users u WHERE username = "Bastian" ORDER BY `u`.`id` LIMIT 1
2024-12-17T09:01:31.131Z        info    authorization/middleware.go:120 middleware.jwt.Unauthorizedcode403messageyou don't have permission to access this resource

2024/12/17 09:01:31 /home/runner/work/donetick/donetick/internal/user/repo/repository.go:62 record not found
[0.223ms] [rows:0] SELECT u.*, 'active' as  subscription, '2999-12-31' as expiration FROM users u WHERE username = "Bastian" ORDER BY `u`.`id` LIMIT 1
2024-12-17T09:01:31.131Z        info    authorization/middleware.go:120 middleware.jwt.Unauthorizedcode403messageyou don't have permission to access this resource

2024/12/17 09:01:31 /home/runner/work/donetick/donetick/internal/user/repo/repository.go:62 record not found
[0.908ms] [rows:0] SELECT u.*, 'active' as  subscription, '2999-12-31' as expiration FROM users u WHERE username = "Bastian" ORDER BY `u`.`id` LIMIT 1
2024-12-17T09:01:31.131Z        info    authorization/middleware.go:120 middleware.jwt.Unauthorizedcode403messageyou don't have permission to access this resource

2024/12/17 09:01:31 /home/runner/work/donetick/donetick/internal/user/repo/repository.go:62 record not found
[0.183ms] [rows:0] SELECT u.*, 'active' as  subscription, '2999-12-31' as expiration FROM users u WHERE username = "Bastian" ORDER BY `u`.`id` LIMIT 1
2024-12-17T09:01:31.134Z        info    authorization/middleware.go:120 middleware.jwt.Unauthorizedcode403messageyou don't have permission to access this resource

**Comment by BastiKA84** [comment]
(As I am a new user, I am not allowed to post more then one pic per post. So thats why directly send the next one.)
So I deleted the docker, cleaned my data with the plugin "CA Cleanup Appdata", deleted the diretory "user/appdata/donetick" and reinstalled the docker.
First: with the reinstall, I got the new variable for the donetick.db. Thats great :) But there is still the typo that in the config path donetick is written with a capital d and in the database path with a small d.
![image](https://github.com/user-attachments/assets/8d5fe169-e965-4eff-b1ba-7729134de476)

But unfortunatly, done does not start anymore, I still get the page with the 404 :( I acutally don't know, from where the app gets the user Bastian. Yes, that one is the user I initially created last week, which I could not log in after the update. And now that user is blocking my to open the app.

**Comment by nwithan8** [comment]
> So I deleted the docker, cleaned my data with the plugin "CA Cleanup Appdata", deleted the diretory "user/appdata/donetick" and reinstalled the docker. First: with the reinstall, I got the new variable for the donetick.db. Thats great :) 

Downloading an app from the Community Apps store behind-the-scenes simply places an XML file in your file system (`/boot/config/plugins/dockerMan/templates/`), and uninstalling the Docker container does not delete this file. And so typically, "re-installing" the container often just reads from the same XML file that's cached on your system. Downloading updated templates on Unraid (not just updating the Docker image for a container, but getting an updated config) therefore requires this process you've discovered of actually clearing out the cache via a plugin or manually.

> But there is still the typo that in the config path donetick is written with a capital d and in the database path with a small d.

This is a weird quirk with Unraid templates, one that I've seen when testing the templates. For whatever reason, sometimes it will respect the path as written in the template (which is typically all lowercase), and other times it will just default to using the name of the app (which is typically title-cased). I promise you, [in the template itself](https://github.com/nwithan8/unraid_templates/blob/91d5c8c540ed17cb340b8272d99a76f46d384087/templates/donetick.xml#L41), it's written as lowercase. This is just something I occasionally have to manually fix, which yes, might not be caught because those config directories are typically under the "Advanced" section because users shouldn't need to change them from their defaults. At the very worst, the template trips up and uses a capital letter and therefore the folder on the filesystem is with a capital letter. Odds are, you aren't navigating via CLI to this folder anyway. 🤷🏻
