### ISSUE TITLE
[Feature Request] User Management Portal

### ISSUE THREAD

**Issue by ados8** [donetick/donetick#43]
I've just begun testing this app to see if I can use it with the home and family.
One thing I noticed right away is no user portal, will this be something on the horizon.
I think it's important for an admin to be able to manage any account that they are hosting, restrict and prevent sign-ups.
This would also eliminate the need to use an SMTP server as the admin can reset passwords for user.
Thank you for developing this app I will continue to review.

Edit:
For now I will block the `/signup` URL and place behind my SSO server for security.

**Comment by meauxt** [comment]
Hi @ados8!  Gonna move this to discussion. right now there is a way to disable signup but user management something not sure if am planning to work on in the meanwhile. maybe in future!
