### ISSUE TITLE
Permissions?

### ISSUE THREAD

**Issue by SuperDarius-git** [donetick/donetick#48]
Good day

I am trying to install on Docker via Docker compose, but when I try to reach the service on my browser, the following logs appear:
```

2024/12/15 08:05:35 /home/runner/work/donetick/donetick/internal/user/repo/repository.go:61 record not found
[0.537ms] [rows:0] SELECT u.*, 'active' as  subscription, '2999-12-31' as expiration FROM users u WHERE username = "superdarius" ORDER BY `u`.`id` LIMIT 1
2024-12-15T08:05:35.729Z        info    authorization/middleware.go:120 middleware.jwt.Unauthorizedcode403messageyou don't have permission to access this resource
```

Please help me.

Thank you Darius

**Comment by SuperDarius-git** [comment]
I thought I found the problem with this, but now after updating the image, it gives me the same error as above. Please help. I just loaded a load of chores with labels, etc. I just started to love this project.

The following error I got in Portainer after I updated the container:
`2024-12-15T20:02:42.620Z	info	authorization/middleware.go:120	middleware.jwt.Unauthorizedcode401messagesignature is invalid`

It also gives me a 404 page when trying to access the page.

Thank you in advance
Darius

**Comment by meauxt** [comment]
this might have to do with your recent cache token and it's no longer valid. trying going to login page by navigating to `/login` and login again and see if that fix the issue

**Comment by SuperDarius-git** [comment]
Thank you so much for your help. I went to the login page and I logged in again, but with no success. It came to the 404 page again. But I then ctrl-F5 to hard refresh the page and that worked. I should've done that from the beginning. I am sorry, but thank you for your help again!
