### ISSUE TITLE
[Bug] - Unable to Create Chores With Circle Members

### ISSUE THREAD

**Issue by mschwerz** [donetick/donetick#49]
I am unable to create chores as part of a circle.

Environment:
- Selfhosted with docker compose

Steps:
1. Create 2 accounts
2. Have account 2 join account 1's circle
3. Go to create a new chore
4. Give a name to the chore
5. Mark both accounts as assignees 
6. Select either account to assign to
7. Create the Chore

Expected:
The chore was able to be created and shows up in the list of chores on the home page

Actual:
Error received saying the chore could not be saved. Error response from the developer console indicates: 400 response with
{"error":"Assignee not found in circle"}

**Comment by meauxt** [comment]
Thank you for reporting this! It should be fixed in [v0.0.23](https://github.com/donetick/donetick/releases/tag/v0.0.23)
