### ISSUE TITLE
Feature Request: Home Assistant Sensors

### ISSUE THREAD

**Issue by ministryofsillywalks** [donetick/donetick#52]
Firstly thanks for the great app!
I'm running it as a home assistant add-on and it works great.
If possible I would love to have the option to integrate tasks directly into home assistant so as to further automate from there.
example:
Use home assistant for notifications on due date. 
Reset tasks by pressing physical buttons.
Use tts to really get me to do things.
etc.
The options are endless.
I see there is an API but a native integration for home assistant would greatly reduce the entry barrier for further automation.
Keep up the great work!

**Comment by binuengoor** [comment]
@ministryofsillywalks going through this now.. how does the integration work? I couldn't figure it out

**Comment by binuengoor** [comment]
nvm found it. For anyone else who might be confused: there’s a Donetick Home Assistant Add-on and a completely separate Donetick Home Assistant Integration. Installing the add-on doesn’t automatically create the integration.

If you prefer, you can self-host Donetick via Docker and still integrate it with Home Assistant. However, the Home Assistant integration seems quite limited—it only includes one sensor that shows the number of chores from Donetick.

For more details, check out: https://github.com/donetick/donetick-hass-integration

**Comment by ados8** [comment]
I'm lost on why the integration exists with no plans to expand it.
Things could be insanely powerful if it had HA integration.
