### ISSUE TITLE
Web sign-up/login page broken (user/password - non-Google)

### ISSUE THREAD

**Issue by n3farious** [donetick/donetick#65]
- Navigate to: https://app.donetick.com/signup 
- Enter required information
- No action performed by site.

(Able to sign-up / log-in using Google.. but prefer user/pw)

Console output from Chromium browsers: 

![image](https://github.com/user-attachments/assets/3fbd50a6-20b2-4fe2-868c-4c8bf8bb130b)

**Comment by meauxt** [comment]
Thank you for reporting this! should be fix in this release!
